name: Build and Test

on:
  push:
    branches: [ $default-branch ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Github Repository
      uses: actions/checkout@v3

    - name: Build
      run: cargo build --release --verbose

    - name: Test
      run: cargo test --verbose
