name: Create Draft Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Checkout Github Repository
      uses: actions/checkout@v3

    - name: Build
      run: cargo build --release --verbose

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/plaintext_to_manuscript*
