name: Publish Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, ubuntu-20.04, windows-latest]

    steps:
    - name: Checkout Github Repository
      uses: actions/checkout@v3

    - name: Build
      run: cargo build --release --verbose

    - name: Rename target file to avoid file name clash in Mac and Linux
      if: matrix.os != 'windows-latest'
      run: |
        [ -f target/release/plaintext_to_manuscript ] && mv target/release/plaintext_to_manuscript target/release/plaintext_to_manuscript_${{ matrix.os }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/plaintext_to_manuscript*
